# Exercise 1.A NumPy: Manipulating Arrays

In [ ]:
import sys
!{sys.executable} -m pip install numpy 
#I was unable to run "import numpy as np", so asked Copilot to assist me to be able to work on my assignments



   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 2.0 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.3 MB 1.9 MB/s eta 0:00:06
   ----- ---------------------------------- 1.6/12.3 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.3 MB 2.2 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.3 MB 2.1 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.3 MB 2.1 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.3 MB 2.2 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.3 MB 2.4 MB/s eta 0:00:04
   ----------------- ---------------------- 5.2/12.3 MB 2.5 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.3 MB 2.6 MB/s eta 0:00:03
   ---------------------- ----------------- 6.8/12.3 MB 2.7 MB/s eta 0:00:03
   ----------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np
np.__version__ #ensured numpy was imported and prompted the version

'2.4.6'

# Looping Through Arrays

In [7]:
arrA = np.array([[11, 12, 13],[14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [9]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [12]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


In the first loop all of the rows were multiplied by 2 and executed in the original row format. The second loop prints every individual element by 2 and returns them individually. 

In [15]:
for x in arrA:
    for y in x:
        loop_result = x * 2
    print(loop_result) #This multiplies the entire row x by 2. The inner loop "for y in x:" runs through each element (y) but is never used. The nested loop does not affect the excuted result. This reult is the same to:
    #for x in arrA:
        #print(x*2)

[22 24 26]
[28 30 32]


## Joining and Stacking Arrays

In [17]:
joined_array_1 = np.concatenate ((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [18]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [19]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [ ]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2), axis=2)
#Got error code saying all aways must have the same shape in order to stack them

ValueError: all input arrays must have the same shape

In [21]:
another_joined_array = np.concatenate((joined_array_1, arrA), axis=0)
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [23]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
#Got an error that said "all the input array dimensions except for the concatenation axis must match exactly" so they were not able to be joined due to not having the same # of rows to concatenate on axis = 1

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [ ]:
var1 = np.hstack((arrA, arrA))
print(var1)   #This executes a horizontal stack, side by side, so it adds columns along its axis
#[[11 12 13 11 12 13]
# [14 15 16 14 15 16]]

var2 = np.vstack((arrA, arrA))
print(var2)   #This executes a vertical stack, on top of each other, so it adds rows along the row axis
#[[11 12 13]
# [14 15 16]
# [11 12 13]
# [14 15 16]]

var3 = np.dstack((arrA, arrA))
print(var3)   #This executes a depth stack, so it puts arrays on top of each other and groups like elements
#[[[11 11]    #So here 11 is grouped
#  [12 12]
#  [13 13]]

# [[14 14]
#  [15 15]
#  [16 16]]]

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [ ]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky) #Execution is 2 arrays and 2 dimensions each

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [ ]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino) #Execution is 3 arrays. The furst array is 2 dimension (2x3). Thesecond is 1x3 so 2D. And the last one is 1x3 as well so 2D.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [37]:
#result_1 = np.where(arrA % 2 == 0, 'odd', 'even') I originally did this and it was wrong so I then added arrA in the odd or even place to view the values, then ralized i had to switch them
result_1 = np.where(arrA % 2 == 0, 'even', 'odd')
print(result_1)

[['odd' 'even' 'odd']
 ['even' 'odd' 'even']]


## Sorting and Filtering Arrays,

In [38]:
arrB = np.array([[7,6],[13,5],[7,3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [44]:
print(arrB)
z = arrB<7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [45]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
