# Exercise 1.B NumPy Random

In [3]:
import numpy as np

## Generating Random Numbers

In [6]:
r_l = np.random.randint(1,20, size=2)
print(r_l)

[8 2]


In [8]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[10  9]]


In [10]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.61481129]
 [0.11621838]]


In [12]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[80 77 39 45 75]
 [69 99 98 50 68]
 [45 84 41 45 59]
 [74 83 27 85 59]]


In [14]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.29119014 0.42634988 0.91824802 0.04699454 0.99798333]
 [0.47731999 0.7425509  0.50011465 0.22488282 0.88828359]
 [0.42383228 0.59034512 0.74134119 0.49867915 0.81856281]
 [0.85108097 0.29394374 0.62714186 0.05085434 0.40169899]]


## Generating Random Choices from an Array

In [16]:
students = np.array(['Onur', 'Longley', 'Jessica', 'Eyerusalem', 'Godknows', 'Rodas', 'Will', 'Kiki', 'Sultan', 'Cagla', 'Paola', 'Mina'])

In [17]:
call_on = np.random.choice(students)
print(call_on)

Godknows


In [ ]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)
#This wouldn't be a good way to generate breakout groups because some names are repetititve

[['Paola' 'Paola' 'Godknows' 'Paola']
 ['Onur' 'Will' 'Will' 'Kiki']
 ['Onur' 'Cagla' 'Rodas' 'Paola']]


In [24]:
call_on_weighted = np.random.choice(students, size=5, p=[0.30,0.10,0.05,0.05,0.00,0.10,0.10,0.10,0.05,0.05,0.00,0.10])
print(call_on_weighted)
#I randomized the probability decimals, I kept gettting errors at first because they did not equal 1, so had to keep track of my math

['Onur' 'Onur' 'Kiki' 'Mina' 'Mina']


## Generating a Normal Distribution

In [25]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[13.06106123  3.920935    9.23790027 15.45113067  9.68968539]
 [15.39969268  7.04752759 17.11065199 11.76187082 11.45013596]
 [ 0.50490575  4.69573929 13.79335044 17.05421531  0.65438151]
 [ 8.42369073 20.23844759 20.91042492  6.62962203  6.82485367]]
