# Exercise 1.C Performing operations on arrays

In [2]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

## Permutations

In [5]:
print(r_4)

[[83 31 84 86 56]
 [25 61 77 57 60]
 [54 26 97 71 53]
 [37 92 89 73 93]]


In [8]:
np.random.shuffle(r_4)
print(r_4)

[[37 92 89 73 93]
 [54 26 97 71 53]
 [83 31 84 86 56]
 [25 61 77 57 60]]


The shuffle only randomized the row order when executed

In [24]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[25 61 77 57 60]
 [83 31 84 86 56]
 [37 92 89 73 93]
 [54 26 97 71 53]]
[[37 92 89 73 93]
 [54 26 97 71 53]
 [83 31 84 86 56]
 [25 61 77 57 60]]


Shuffle mdofifies the original array and the permutation leaves the original array alone. You can use shuffle when you don't need the original order and the permutation when you need to keep the original array intact.

## Mathematical Operations

In [26]:
print(r_1)
print(r_1.shape)
print(r_2)
print(r_2.shape)
print(np.add(r_1,r_2))

[13 16]
(2,)
[[11  4]]
(1, 2)
[[24 20]]


In [27]:
print(r_1)
print(r_1.shape)
print(r_3)
print(r_3.shape)
print(np.add(r_1,r_3))

[13 16]
(2,)
[[0.078321  ]
 [0.71724448]]
(2, 1)
[[13.078321   16.078321  ]
 [13.71724448 16.71724448]]


In [ ]:
print(r_2)
print(r_2.shape)
print(r_4)
print(r_4.shape)
print(np.add(r_2,r_4)) #Got an error because they are both different shapes and cannot be added together

[[11  4]]
(1, 2)
[[37 92 89 73 93]
 [54 26 97 71 53]
 [83 31 84 86 56]
 [25 61 77 57 60]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [30]:
print(np.add(r_4, np.array([1])))

[[38 93 90 74 94]
 [55 27 98 72 54]
 [84 32 85 87 57]
 [26 62 78 58 61]]


In [ ]:
print(np.add(r_4, np.array([[1]]))) #The same as if it was just one []

[[38 93 90 74 94]
 [55 27 98 72 54]
 [84 32 85 87 57]
 [26 62 78 58 61]]


In [32]:
print(np.add(r_4, np.array([1, 1, 1, 1, 1])))

[[38 93 90 74 94]
 [55 27 98 72 54]
 [84 32 85 87 57]
 [26 62 78 58 61]]


In [ ]:
print(np.add(r_4, np.array([[1], [1]]))) #Got an error message due to differences in array shapes and since neither is a size of 1 array (to be expanded) it executed an error

ValueError: operands could not be broadcast together with shapes (4,5) (2,1) 

Broadcasting lets you add two different sized arrays (shapes) by expanding the smaller one. 

## Rounding

In [35]:
print(r_3)

[[0.078321  ]
 [0.71724448]]


In [36]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [37]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [40]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [41]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [42]:
print(np.round(r_3, 2))

[[0.08]
 [0.72]]


## Cumulative Operations

In [43]:
print(r_4)

[[37 92 89 73 93]
 [54 26 97 71 53]
 [83 31 84 86 56]
 [25 61 77 57 60]]


In [45]:
print(np.sum(r_4))

1305


In [46]:
print(np.sum(r_4, axis=0))

[199 210 347 287 262]


In [47]:
print(np.sum(r_4, axis=1))

[384 301 340 280]


In [50]:
print(np.cumsum(r_4))

[  37  129  218  291  384  438  464  561  632  685  768  799  883  969
 1025 1050 1111 1188 1245 1305]


In [51]:
print(np.cumsum(r_4, axis=0))

[[ 37  92  89  73  93]
 [ 91 118 186 144 146]
 [174 149 270 230 202]
 [199 210 347 287 262]]


## Grocery Problem.

In [57]:
bag1 = np.array([2, 3, 4, 0])  
bag2 = np.array([4, 0, 1, 2])
print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [60]:
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)
print(f'The first bag contains {total_bag1} items and the second bag contains {total_bag2} items.')

The first bag contains 9 items and the second bag contains 7 items.


In [65]:
total_categories = bag1 + bag2
veg, fruit, snacks, bev = total_categories
print(f'There are {veg} vegetables, {fruit} fruits, {snacks} boxes of snacks, and {bev} beverages in the two grocery bags')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags


## Teamwork

In [66]:
#Ali reported knocking on 5 doors on Monday, 4 on Tuesday, 6 on Wednesday, 4 on Thursday, and 2 on Friday. Create a variable holding an array of these values.
ali = np.array([5, 4, 6, 4, 2])

In [67]:
#Ben missed Monday because he was out of town. He reported knocking on 5 on Tuesday, 5 on Wednesday, 3 on Thursday, and 4 on Friday. Create a variable holding an array of Ben’s values.
ben = np.array([0, 5, 5, 3, 4])

In [68]:
#Carla reported knocking on 3 doors on Monday, 6 on Tuesday, 3 on Thursday, and 4 on Friday. She was sick on Wednesday so missed that day. Create a variable holding an array of Carla’s values.
carla = np.array([3, 6, 0, 3, 4])

In [73]:
#Compile the values reported by Ali, Ben, and Carla into a single array containing all door-knocks for the week, as all_knocks. Print the resulting array.
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [80]:
#Use all_knocks to calculate the total number of doors that each person knocked on for the week, and also the total number of doors that the group collectively knocked on. Print the results.
total_per_person = np.sum(all_knocks, axis=1)
total_group = np.sum(all_knocks)

print(total_per_person)
print(total_group)

[21 17 16]
54


In [89]:
#The organization you’re working with estimates that for every two door-knocks, one of those people will actually turn out to vote. For your report to the organization, what is the rolling total of estimated votes that your group was able to turn out, day by day for last week? (Hint: Start with the rolling total by day, then multiply that array by an appropriate value to get the result.)
daily_totals = np.sum(all_knocks, axis=0)
rolling_knocks = np.cumsum(daily_totals)
estimated_votes = rolling_knocks * 0.5
results = np.vstack([daily_totals, rolling_knocks, estimated_votes])
print(results)



[[ 8.  15.  11.  10.  10. ]
 [ 8.  23.  34.  44.  54. ]
 [ 4.  11.5 17.  22.  27. ]]
